feature: added question crud
RIP-Comm/AMAlanche pull request #17
Opened 2022-11-26 10:16 UTC by bozzelliandrea

CRUD Implementation for the task #14

2022-11-26 15:41 UTC, datge commented on src/routes/question.ts
> +        .post((req: Request, res: Response, next: NextFunction) => {
Here is missing the validation part, check the user route, i would also suggest to use the customError and the customSuccess, otherwise  we are not gonna have a standard for errors and success json responses

2022-11-26 15:46 UTC, SimOneGollo requested changes

2022-11-26 15:46 UTC, SimOneGollo commented on src/routes/question.ts
> +        .post((req: Request, res: Response, next: NextFunction) => {
Missing body validation

2022-11-26 15:46 UTC, SimOneGollo commented on src/routes/question.ts
> +        .put((req: Request, res: Response, next: NextFunction) => {
missing body validation

2022-11-26 15:46 UTC, SimOneGollo commented on src/services/question.ts
> +            throw new CustomError(404, "Raw", "Entity not found!");
CustomError should not be in QuestionService, but it must be in Question route handler. In this function return null if no question is found.

This comment is valid for all file.

2022-11-26 15:48 UTC, datge commented on src/services/question.ts
> +    public async create(question: IQuestion): Promise<IQuestion> {
The interface should be a create one (without _id, create)

2022-11-26 15:48 UTC, datge commented on src/services/question.ts
> +    public async update(question: IQuestion): Promise<IQuestion> {
Like before

2022-11-27 09:02 UTC, bozzelliandrea commented on src/services/question.ts
> +    public async create(question: IQuestion): Promise<IQuestion> {
interfaces in typescript have optional field, so you can use the same interface without split in 2/3 version of the same object

2022-11-27 09:04 UTC, bozzelliandrea commented on src/services/question.ts
> +            throw new CustomError(404, "Raw", "Entity not found!");
why not throw the error from the service? which is the class working with repository/database layer

2023-10-07 17:30 UTC, closed without merging