Register
RIP-Comm/AMAlanche pull request #49
Opened 2023-10-12 10:55 UTC by Chineee

created routes package and controllers package
Implemented POST for route /users.
Created UserEntity

2023-10-12 18:39 UTC, Zlays requested changes

2023-10-12 18:39 UTC, Zlays commented on backend/main.go
> +	if err := godotenv.Load(".env"); err != nil {
Currently we were reading the project variables from "properties.yaml", but if we want to use ".env", we can refactor the whole process. 
In any case, I would move the control to the config.go file.

2023-10-12 18:39 UTC, Zlays commented on backend/controllers/user.go
> +	if err := dbInstance.DB.Create(&user).Error; err != nil {
I would move these pieces of code to a service package so that they can be reused in other parts of the code, such as for access through other providers.

2023-10-12 18:39 UTC, Zlays commented on backend/controllers/user.go
> +	refreshToken, _ := jwt.NewWithClaims(jwt.SigningMethodHS256, token).SignedString([]byte(os.Getenv("SECRET_REFRESH_KEY")))
The distribution of variables must be done through the ConfigProvider, in this case within SecurityConfig.

2023-10-12 18:44 UTC, Zlays requested changes

2023-10-12 18:44 UTC, Zlays commented on backend/controllers/user.go
> +	}
I would move these types of code pieces into a service package so that they can be reused in other parts of the code, such as for access through other providers.

2023-10-12 20:13 UTC, guerinoni requested changes
I also suggest to run fmt on the code :)

2023-10-12 20:13 UTC, guerinoni commented on backend/controllers/user.go
> +}
Why?

2023-10-12 20:13 UTC, guerinoni commented on backend/controllers/user.go
> +	dbInstance := configs.GetDBInstance()
Move this after validation of payload

2023-10-12 20:13 UTC, guerinoni commented on backend/controllers/user.go
> +		c.JSON(http.StatusBadRequest, gin.H{"message": "username or password wrong"})
This is not bad request, this is bad input

2023-10-12 20:13 UTC, guerinoni commented on backend/controllers/user.go
> +	token["exp"] = time.Now().Add(time.Minute * 5).Unix()
Expiration should be at least 3h, wdyt? Let's think of a live event, doesn't make any sense 5m

2023-10-12 20:13 UTC, guerinoni commented on backend/controllers/user.go
> +	}
If there's an error we continue?

2023-10-12 20:13 UTC, guerinoni commented on backend/controllers/user.go
> +	dbInstance := configs.GetDBInstance()
Same as above

2023-10-12 20:13 UTC, guerinoni commented on backend/controllers/user.go
> +		c.JSON(http.StatusBadRequest, gin.H{"error": true, "status": 500, "message": err})
Missing return?

2023-10-12 20:13 UTC, guerinoni commented on backend/controllers/user.go
> +}
?

2023-10-12 20:13 UTC, guerinoni commented on backend/main.go
> +
?

2023-10-12 20:13 UTC, guerinoni commented on backend/main.go
> +	if err := godotenv.Load(".env"); err != nil {
What is the benefit of properties.yaml vs .env?

2023-10-12 20:13 UTC, guerinoni commented on backend/main.go
> +		fmt.Println("ICAOOOOO")
?

2023-10-12 20:13 UTC, guerinoni commented on backend/routes/users.go
> +	router.GET("/login", controllers.Login)
I don't think we need all of those

2023-10-12 20:19 UTC, Chineee commented on backend/controllers/user.go
> +	token["exp"] = time.Now().Add(time.Minute * 5).Unix()
Access token will be stored in the local storage, when access token expires web app will do a request to an endpoint /token passing the refresh token which lives 8h, if refresh tokens is valid it will generate a new access token that will be stored in local storage replacing the old one

2023-10-12 20:21 UTC, guerinoni commented on backend/controllers/user.go
> +	token["exp"] = time.Now().Add(time.Minute * 5).Unix()
Make sense, but probably for this kind of problem it is enough a single token with exp 3/4h, for the next event you can also do a new login :)

2023-10-12 20:35 UTC, Chineee commented on backend/main.go
> +		fmt.Println("ICAOOOOO")
Forgot remove printf when trying to run the app the first time

2023-10-12 20:54 UTC, Zlays commented on backend/main.go
> +	if err := godotenv.Load(".env"); err != nil {
Yaml is structured and more readable while ".env" is plain text.
We can also add the following script to the beginning of "loadConfig" giving the possibility to override yaml environment variables via ".env.local" in addition to environment variables:  
(in this case I would no longer upload the ".env" file to the repository and add the variables inside the yaml)
`
func (p *ConfigProvider) loadConfig() {
	if err := godotenv.Load(".env"); err != nil {
		panic(fmt.Errorf(utils.StartupError, err))
	}
`

2023-10-12 21:57 UTC, guerinoni commented on backend/main.go
> +	if err := godotenv.Load(".env"); err != nil {
Go for yml

2023-10-13 14:50 UTC, Chineee commented on backend/controllers/user.go
> +	}
fixed

2023-10-13 14:55 UTC, Chineee commented on backend/controllers/user.go
> +	token["exp"] = time.Now().Add(time.Minute * 5).Unix()
Should we store the single token in the cookie or in the local storage?
Considering localstorage is immune to CSRF but not to XSS whereas Cookies are immune to XSS (http only) but not to CSRF

2023-10-13 16:51 UTC, Zlays approved these changes

2023-10-13 17:02 UTC, Chineee commented on backend/controllers/user.go
> +}
Removed didn't saw that

2023-10-13 17:06 UTC, Chineee commented on backend/controllers/user.go
> +		c.JSON(http.StatusBadRequest, gin.H{"message": "username or password wrong"})
Which status code should we use? There isn't one for bad input

2023-10-14 07:27 UTC, guerinoni commented on backend/controllers/user.go
> +	token["exp"] = time.Now().Add(time.Minute * 5).Unix()
What if this flow:
- login
- receive token after login+validation
- keep token in the code as a variable and pass through all request

Too simple?

2023-10-14 09:46 UTC, Chineee commented on backend/controllers/user.go
> +	token["exp"] = time.Now().Add(time.Minute * 5).Unix()
In the code you mean in FE right? Is so we could do that, but then user must do a login everytime he closes and open the application

2023-10-14 09:49 UTC, guerinoni commented on backend/controllers/user.go
> +	token["exp"] = time.Now().Add(time.Minute * 5).Unix()
It is ok for now, let re-login every time you need, if you use this 2/months it is ok do it... In future we can improve this...

2023-10-14 11:08 UTC, guerinoni approved these changes

2023-10-14 11:08 UTC, merged